import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import { CookiesProvider } from 'next-client-cookies/server'
import Header from './components/Header/inedx'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" data-theme="cupcake">
      <body className={inter.className}>
       <Header/>
        <main>  
          <CookiesProvider>
            {children}
         </CookiesProvider>
        </main>
        <footer></footer>
        </body>
    </html>
  )
}
