import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import { CookiesProvider } from 'next-client-cookies/server'
import Header from './components/Header/inedx'
import Footer from './components/Footer'
import CookieBanner from './components/CookieBanner'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" data-theme="cupcake">
      <body className={inter.className }>
      <div className="container flex flex-col min-h-screen mx-auto">
       <Header/>
         <CookiesProvider>
         <CookieBanner/>
          <main className='flex-grow container'> 
             
              {children}
          </main>
         </CookiesProvider>
       
       <Footer/>
       </div>
        </body>
    </html>
  )
}
