import type { Metadata } from 'next'
import { Cairo } from 'next/font/google'
import './globals.css'
import { CookiesProvider } from 'next-client-cookies/server'
import Header from './components/Header/inedx'
import Footer from './components/Footer'
import CookieBanner from './components/CookieBanner'

const cairo = Cairo({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" data-theme="cupcake">
      <body className={cairo.className }>
      <div className="flex flex-col min-h-screen mx-auto max-w-7xl">
     
         <CookiesProvider>
         <Header/>
         <CookieBanner/>
          <main className='flex-grow  grid'> 
             
              {children}
          </main>
          <Footer/>
         </CookiesProvider>
       
       
       </div>
        </body>
    </html>
  )
}
